import { google } from 'googleapis';
import { DateTime, Interval } from 'luxon';

const TIME_ZONE = process.env.BUSINESS_TIMEZONE || 'America/Chicago';
const CALENDAR_ID = process.env.GOOGLE_CALENDAR_ID || 'ysamia41@gmail.com';

const BUSINESS_HOURS = {
  1: ['09:00', '18:00'],
  2: ['09:00', '18:00'],
  3: ['09:00', '18:00'],
  4: ['09:00', '18:00'],
  5: ['09:00', '18:00'],
  6: ['09:00', '18:00']
};

const SERVICES = {
  'shell-shine-basic': { name: 'Shell Shine Basic', price: '$70+', duration: 60 },
  'exterior-detail': { name: 'Exterior Detail', price: '$50–$80', duration: 90 },
  'interior-detail': { name: 'Interior Detail', price: '$100+', duration: 120 },
  'full-detail': { name: 'Full Detail', price: '$150–$180', duration: 180 },
  'golden-shell-pack': { name: 'Golden Shell Pack', price: '$300', duration: 240 }
};

function getCalendarClient() {
  if (!process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL || !process.env.GOOGLE_PRIVATE_KEY || !CALENDAR_ID) {
    throw new Error('Calendar environment variables are not configured.');
  }

  const auth = new google.auth.GoogleAuth({
    credentials: {
      client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
      private_key: process.env.GOOGLE_PRIVATE_KEY.replace(/\\n/g, '\n')
    },
    scopes: ['https://www.googleapis.com/auth/calendar']
  });

  return google.calendar({ version: 'v3', auth });
}

function clean(value, max = 1000) {
  return String(value || '').trim().slice(0, max);
}

function validEmail(email) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST');
    return res.status(405).json({ error: 'Method not allowed.' });
  }

  try {
    const service = SERVICES[req.body?.service];
    if (!service) return res.status(400).json({ error: 'Please select a valid service.' });

    const name = clean(req.body.name, 120);
    const email = clean(req.body.email, 180).toLowerCase();
    const phone = clean(req.body.phone, 60);
    const vehicle = clean(req.body.vehicle, 180);
    const location = clean(req.body.location, 300);
    const notes = clean(req.body.notes, 1500);
    const requestedStart = clean(req.body.start, 80);

    if (!name || !email || !phone || !vehicle || !requestedStart) {
      return res.status(400).json({ error: 'Please complete all required fields.' });
    }
    if (!validEmail(email)) return res.status(400).json({ error: 'Please enter a valid email address.' });

    const start = DateTime.fromISO(requestedStart, { setZone: true }).setZone(TIME_ZONE);
    if (!start.isValid) return res.status(400).json({ error: 'Please choose a valid appointment time.' });

    // Only accept half-hour slots generated by the availability endpoint.
    if (![0, 30].includes(start.minute) || start.second !== 0) {
      return res.status(400).json({ error: 'Please choose an available appointment time.' });
    }

    const now = DateTime.now().setZone(TIME_ZONE);
    if (start < now.plus({ minutes: 60 })) {
      return res.status(409).json({ error: 'That time is too close to the current time. Please choose another slot.' });
    }
    if (start > now.plus({ days: 60 })) {
      return res.status(400).json({ error: 'Bookings are available up to 60 days ahead.' });
    }

    const end = start.plus({ minutes: service.duration });
    const hours = BUSINESS_HOURS[start.weekday];
    if (!hours) return res.status(400).json({ error: 'SoSlow Detailing is not accepting online bookings that day.' });

    const open = DateTime.fromISO(`${start.toISODate()}T${hours[0]}`, { zone: TIME_ZONE });
    const close = DateTime.fromISO(`${start.toISODate()}T${hours[1]}`, { zone: TIME_ZONE });
    if (start < open || end > close) return res.status(400).json({ error: 'Please choose a time within business hours.' });

    const calendar = getCalendarClient();

    // Re-check the slot immediately before creating the event to reduce double-bookings.
    const freeBusy = await calendar.freebusy.query({
      requestBody: {
        timeMin: start.toUTC().toISO(),
        timeMax: end.toUTC().toISO(),
        timeZone: TIME_ZONE,
        items: [{ id: CALENDAR_ID }]
      }
    });

    const busy = freeBusy.data.calendars?.[CALENDAR_ID]?.busy || [];
    const requestedInterval = Interval.fromDateTimes(start, end);
    const conflict = busy.some(item =>
      Interval.fromDateTimes(DateTime.fromISO(item.start), DateTime.fromISO(item.end)).overlaps(requestedInterval)
    );

    if (conflict) {
      return res.status(409).json({ error: 'That appointment was just taken. Please choose another time.' });
    }

    const description = [
      `Customer: ${name}`,
      `Email: ${email}`,
      `Phone: ${phone}`,
      `Vehicle: ${vehicle}`,
      `Service: ${service.name}`,
      `Displayed price: ${service.price}`,
      location ? `Service location: ${location}` : '',
      notes ? `Notes: ${notes}` : ''
    ].filter(Boolean).join('\n');

    const created = await calendar.events.insert({
      calendarId: CALENDAR_ID,
      requestBody: {
        summary: `${service.name} — ${name}`,
        description,
        location: location || undefined,
        start: {
          dateTime: start.toISO(),
          timeZone: TIME_ZONE
        },
        end: {
          dateTime: end.toISO(),
          timeZone: TIME_ZONE
        },
        extendedProperties: {
          private: {
            source: 'soslowdetailing.com',
            customerEmail: email,
            customerPhone: phone,
            vehicle
          }
        }
      }
    });

    return res.status(201).json({
      ok: true,
      eventId: created.data.id,
      displayTime: `${start.toFormat('cccc, LLLL d')} at ${start.toFormat('h:mm a')}`
    });
  } catch (error) {
    console.error(error);
    return res.status(500).json({ error: 'Could not create the appointment right now. Please try again.' });
  }
}
